-- Struktura bazy danych dla aplikacji CCActive
-- wykonywać z użytkownika: ccactive_user

-- Tabela: ROLES

-- DROP TABLES jeśli potrzebne:
-- DROP TABLE work_sessions CASCADE CONSTRAINTS;
-- DROP TABLE status_logs CASCADE CONSTRAINTS;
-- DROP TABLE statuses CASCADE CONSTRAINTS;
-- DROP TABLE users CASCADE CONSTRAINTS;
-- DROP TABLE roles CASCADE CONSTRAINTS;


CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE
);

-- Tabela: USERS
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(256) NOT NULL,
    role_id NUMBER NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

-- Tabela: STATUSES
CREATE TABLE statuses (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(100)
);

-- Tabela: STATUS_LOGS (historia zmian statusów agentów)
CREATE TABLE status_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    status_id NUMBER NOT NULL,
    timestamp_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    timestamp_end TIMESTAMP,
    source VARCHAR2(20) DEFAULT 'manual',
    external_call_id VARCHAR2(50),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (status_id) REFERENCES statuses(status_id)
);

-- Tabela: WORK_SESSIONS - logowania i wylogowania
CREATE TABLE work_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Testowe role
INSERT INTO roles (role_name) VALUES ('agent');
INSERT INTO roles (role_name) VALUES ('admin');

-- Testowe statusy
INSERT INTO statuses (status_name, description) VALUES ('Dostępny', 'Gotowy do przyjęcia połączenia');
INSERT INTO statuses (status_name, description) VALUES ('Rozmowa', 'W trakcie połączenia');
INSERT INTO statuses (status_name, description) VALUES ('Przerwa', 'Dowolna przerwa (prywatna lub służbowa)');
INSERT INTO statuses (status_name, description) VALUES ('Offline', 'Poza systemem');